version: '3.8'

services:
  # Vextir OS Event Processor
  vextir-os:
    image: python:3.10-slim
    working_dir: /app
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - OPENAI_MODEL=${OPENAI_MODEL:-gpt-3.5-turbo}
      - PYTHONUNBUFFERED=1
      - PYTHONPATH=/app
    volumes:
      - .:/app
    command: |
      bash -c "
        pip install -e .[local] && 
        python run_vextir_os.py
      "
    networks:
      - vextir-net

  # CLI Client (for testing)
  vextir-cli:
    image: python:3.10-slim
    working_dir: /app
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - PYTHONUNBUFFERED=1
      - PYTHONPATH=/app
    volumes:
      - .:/app
    networks:
      - vextir-net
    depends_on:
      - vextir-os
    stdin_open: true
    tty: true
    command: |
      bash -c "
        pip install -e .[local] && 
        echo 'Vextir CLI ready. Run: python test_event_chat.py' && 
        bash
      "

networks:
  vextir-net:
    driver: bridge